SLACK_CHANNEL_NAME: build-status
ENVIRONMENT: prod
CODE_BASE_PATH: Assignment-6
ACTION_MESSAGE: "Ansible deployment for Assignment6"
KEEP_APPROVAL_STAGE: true

GIT:
  URL: https://github.com/Mehak-gupta23/ansible-repo.git
  BRANCH: main
  CREDENTIALS_ID: git-credits

ANSIBLE:
  PLAYBOOK: site.yml


